### ISSUE TITLE
Error Occurred in Plugin using Grafana Cloud with Managed Pixie

### ISSUE THREAD

**Issue by AobaIwaki123** [pixie-io/grafana-plugin#100]
I'm using Managed Pixie in Cosmic Cloud with local k8s cluster.
And I'm using Grafana Cloud now. 
Both Pixie and Grafana are free plan.
I tried to make dashboard on Grafana Cloud, for example [px-cluster](https://github.com/pixie-io/grafana-plugin/blob/main/dashboards/px_cluster.json),
I can see my px-cluster on Cosmic Cloud, below.
But I can not see that on Grafana Cloud. 
What did I miss?

![image](https://github.com/user-attachments/assets/e2d7b5a9-3cd7-4f35-8c91-94458ea4d69f)

**Comment by ddelnano** [comment]
Hi @AobaIwaki123, are you able to share information on what you are seeing on the Grafana cloud side when you try to create that dashboard? Have you tried any other Pixie grafana plugin dashboards?

**Comment by ddelnano** [comment]
And just to confirm, you set the Pixie API key, Cluster ID and Cloud address (as mentioned in Step 5 from [here](https://docs.px.dev/tutorials/integrations/grafana/))?

I think the plugin might default to the New Relic cloud address (withpixie.ai) instead of the Cosmic one.

**Comment by AobaIwaki123** [comment]
@ddelnano 
Thanks! I missed "Cloud address"
It said "Connection to Pixie cluster successfully configured", so I didn't notice I missed URL.
I want to know the example of API URL of the Cosmic one if you know.

<img width="829" alt="image" src="https://github.com/user-attachments/assets/4527a1d9-352a-4515-b38d-748c82fd5c83">

**Comment by ddelnano** [comment]
@AobaIwaki123 it should be `work.getcosmic.ai:443` or `getcosmic.ai:443`. 

After looking into the logic that triggers the `Connection to Pixie cluster successfully configured` message, I don't believe it validates that the credentials work ([source](https://github.com/pixie-io/grafana-plugin/blob/cb0d00ecea7a388841788d81ddd3d56bd5a15e6b/pkg/pixie_plugin.go#L204-L227)). Since the default `withpixie.ai` is a valid cloud address the simple check it does is likely successful even if the credentials are invalid.

If fixing the cloud address solves the issue, we should repurpose this issue to track providing better error output and sanity checking when these configurable options are saved and tested.

**Comment by AobaIwaki123** [comment]
@ddelnano 
Thanks! work.getcosmic.ai:443 or getcosmic.ai:443 are both working in my environment.

But I noticed there is other problem.
After I pushed the button "save&test", the Cloud address which I filled is deleted.
However, datasource is working correctly.
So, it's not a problem to use datasource but it will confuse most users.

<img width="803" alt="image" src="https://github.com/user-attachments/assets/4da08d68-253b-4064-9293-1a39852c982c">

**Comment by ddelnano** [comment]
@AobaIwaki123 thanks for confirming that fixed the issue and I see what you mean. I believe this is because the plugin is storing the cloud address in the `secretJsonData` property. These values are encrypted by Grafana and aren't able to be read back out, which means [this](https://github.com/pixie-io/grafana-plugin/blob/cb0d00ecea7a388841788d81ddd3d56bd5a15e6b/src/config_editor.tsx#L155) will always be an empty string.

I'm working on a fix for this and hope to have a PR open soon.

**Comment by AobaIwaki123** [comment]
@ddelnano 
Thanks a lot!

**Comment by ddelnano** [comment]
It took some time for me to re-gain access to our Grafana cloud account (was using an email from previous employer), but with that squared away the v0.10.0 release will be out with this fix soon!
